baseURL = "https://simplygooddentistry.com/"
description = "Simply Good Dentistry is the dental practice of Les Kicklighter, DMD. Based in Statesboro, Georgia and located one block north of Howard Lumber Company in the Gentilly Office Complex, we are dedicated to bringing back the luster of one on one dentistry."
languageCode = "en-us"
theme = "site-theme"
title = "Simply Good Dentistry"
[[menu.desktop]]
identifier = "services"
name = "Services"
url = "/services"
weight = 1
[[menu.desktop]]
identifier = "aboutus"
name = "About Us"
url = "/about-us"
weight = 2
[[menu.desktop]]
identifier = "contactus"
name = "Contact Us"
url = "/contact-us"
weight = 3
[[menu.desktop]]
identifier = "patients"
name = "Patients"
url = "/patients"
weight = 4
[[menu.mobile]]
identifier = "aboutus"
name = "About Us"
url = "/about-us"
weight = 1
[[menu.mobile]]
identifier = "contactus"
name = "Contact Us"
url = "/contact-us"
weight = 2
[[menu.mobile]]
identifier = "patients"
name = "Patients"
url = "/patients"
weight = 3
[[menu.services]]
identifier = "preventative-oral-health"
name = "Preventative Oral Health"
url = "/preventative-oral-health"
weight = 1
[[menu.services]]
identifier = "gum-disease-treatment"
name = "Gum Disease Treatment"
url = "/gum-disease-treatment"
weight = 2
[[menu.services]]
identifier = "restorative-services"
name = "Restorative Services"
url = "/restorative-services"
weight = 3
[[menu.services]]
identifier = "specialty-services"
name = "Specialty Services"
url = "/specialty-services"
weight = 4
[params.Contact_Numbers]
Fax = "912.764.8850"
Phone = "912.489.4151"
[params.Logos]
dark_logo = "/pageimg/SGD.Horizontal.Solid.Black.svg"
logo = "/pageimg/SGD.Logo.Light.svg"
mobile_menu_logo = "/pageimg/SGD.Horizontal.Color.Dark.svg"
[params.address]
city = "Statesboro"
state = "GA"
street = "512 Gentilly Road"
zip = 30458
[params.contact_numbers]
fax = "912.764.8850"
phone = "912.489.4151"
[params.email]
email = "leskicklighterdmd@live.com"
[params.logos]
dark_logo = "/pageimg/SGD.Horizontal.Solid.Black.svg"
footer_logo = "/pageimg/SGD.Horizontal.Color.Dark.svg"
logo = "/pageimg/SGD.Logo.Light.svg"
mobile_menu_logo = "/pageimg/SGD.Horizontal.Color.Dark.svg"
[params.office_info]
details = "Closed daily for lunch from 1:00pm - 2:00pm"
[params.office_info.days_open]
end_of_week = "Thursday"
start_of_week = "Monday"
[params.office_info.hours_open]
end_of_day = "5:00 pm"
start_of_day = "8:00 am"
