---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Site Globals
- type: directory
  path: themes/site-theme/data/treatment_list
  label: Treatment List
  create: documents
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "**-treatments.md"
- type: directory
  path: content
  label: Home Page
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/pageimg"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
